[package]
name = "waydows-base"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
rand = { version = "0.8.5", features = ["small_rng"] }
waydows-unix-socket = { version = "0.1.0", path = "../unix-socket" }
