[package]
name = "waydows-base"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
hv_sock = { git = "https://github.com/ALinuxPerson/hv_sock.git", version = "0.1.0" }
rand = { version = "0.8.5", features = ["small_rng"] }
