[package]
name = "hv-sock"
version = "0.1.0"
edition = "2021"

[dependencies]
getset = "0.1.2"
uuid = { version = "1.10.0", features = ["v4"] }
windows = { version = "0.58.0", features = ["Win32_System_Hypervisor"] }
windows-registry = "0.2.0"
windows-result = "0.2.0"
