[package]
name = "hv-sock"
version = "0.1.0"
edition = "2021"

[dependencies]
getset = "0.1.2"

[target."cfg(windows)".dependencies]
uuid = { version = "1.10.0", features = ["v4"] }
windows-registry = "0.2.0"
windows-result = "0.2.0"
